server:
  port: 9000
spring:
  application:
    name: api-gateway
  profiles:
    active: default
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**
            - id: mail-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/otp/**
            - id: vault-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/vault/**