spring.application.name=vault-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/db_vault
spring.datasource.username=fanbo
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect